### PR TITLE
I think I solved the whole issue.

### PR DESCRIPTION
**Pull request by MichaelElbert**
I fixed the youtube title getting, all I had to do was look at the code and comment it out like frogger said.

### CODE REVIEW

**Comment by correcthorsebatterystaple-sudo** [comment]
Please use /\* this */ for  multi line comments, but i kek'd.

**Comment by MichaelElbert** [comment]
Oi you fucken bastard, merge it or I'll pop your wee eyes out.

**Comment by MichaelElbert** [comment]
Yeah too high to be on github.

**Comment by FroggMaster** [comment]
I'm just going to comment out some further shit here. I'll do dis manually.

**Pull request closed without merging**
