### PR TITLE
Bruno's huge pull request

### PR DESCRIPTION
**Pull request by Bruno02468**
Fixes  server.js indentation
Fixes server.js syntax issues
Fixes code repetition for 2Spooks
Adds rock-paper-scissors

### CODE REVIEW

**Comment by ghost** [comment]
good jaab good jaab clapclapclapap
thank america

**Comment by correcthorsebatterystaple-sudo** [comment]
Your boiler plate fix is shit, but merging bcuz RPS. 
You better have tested this ahead of time.

**Comment by ghost** [comment]
so salty <3

**Comment by FroggMaster** [comment]
Pulled dis; Will update soon.

**Pull request merged**
